### ISSUE TITLE
timespec redefinition error

### ISSUE THREAD

**Issue by FancyBanana** [pbatard/libusbx-hp#1]
Hi,
I had timespec type redefinition error while trying to compile your project in Visual Studio Community 2015. I've added following lines into `config.h`

```
#if( defined(_MSC_VER) && _MSC_VER >= 1900)
#define HAVE_STRUCT_TIMESPEC 1
#endif
```

I'm not sure if this fixes the problem universally but it worked for me.

**Comment by pbatard** [comment]
That's great, but this project is **unmaintained**, so there will only be more and more errors like this. Also it is missing all the VERY IMPORTANT bugfixes from the latest libusb, so you really shouldn't use it.
